### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_3_moment__ is not a function

### ISSUE THREAD

**Issue by shamank** [HsuanXyz/ion2-calendar#83]
I'm facing this error after updating from 2.0.0-beta.3 to master branch. Any suggestions please?

**Comment by shamank** [comment]
Sorry, I'm using it the old way (importing CalendarController from ion2-calendar/dist). I'll try with the new Modal mode and I'll let you know. Preserve this issue please, thanks.

**Comment by shamank** [comment]
Nop, just updated as docs said and I got the same error.

```
import { ModalController } from 'ionic-angular';
import { CalendarModal } from 'ion2-calendar';
...

constructor(protected _modalCtrl: ModalController)
...

let calendar = this._modalCtrl.create(CalendarModal, { options: { title: 'BASIC' } });                                                                              
calendar.present();
```

Any ideas please? Thanks.

**Comment by shamank** [comment]
I think it might be related to moment 2.19 (you are using 2.18.1 in your demo and tests). https://github.com/moment/moment/issues/4218

**Comment by C-V-K-D** [comment]
I'm facing the exact same error and trying to fix it for the entire afternoon but couldn't find a solution.
I've tried yours (ie to downgrade moment to 2.18.1 instead of 2.19) and it works, so thank you very much, you saved my day until this issue is fixed !

**Comment by shamank** [comment]
@HsuanXyz In the link some people suggest aliasing moment in webpack config, like this:
```
  resolve: {
    alias: {
      'moment$': 'moment/moment',
    },
  },
```
Unfortunately, I'm not sure on how to achieve this in Ionic, since you can't access/overwrite in "dependency way" webpack config from your own plugin config (https://stackoverflow.com/questions/41512923/how-to-extend-default-webpack-config-in-ionic-v2).

Other users just replaced moment dependecies from moment to moment/moment and so on (in case you have more than one import in your app, like with timezone or other moment feature). Can you try that?

**Comment by HsuanXyz** [comment]
@shamank Hi, Thank you for your help, now you can upgrade latest version for moment fix this bug.

`npm i moment@2.19.1 --save` https://github.com/moment/moment/pull/4225

Thanks again !

**Comment by shamank** [comment]
Great! It works now, thanks!
